### ISSUE TITLE
Syntax error in Webstorm

### ISSUE THREAD

**Issue by smallg** [ruanyf/react-demos#18]
![image](https://cloud.githubusercontent.com/assets/225962/13517294/fb38a70e-e1fc-11e5-9d02-76aac13434d4.png)
how to fix it?
thank you

**Comment by flyfy1** [comment]
@smallg Choose JSX Harmony in `Languages & Frameworks -> JavaScript > Language Version`
![image](https://cloud.githubusercontent.com/assets/1553760/13517320/4a99c4cc-e1fd-11e5-9684-91b6dc3698de.png)

**Comment by smallg** [comment]
@flyfy1 still can not work.

**Comment by ruanyf** [comment]
sorry, I use Vim. Don't know how to use other editors.
