### ISSUE TITLE
mac os 下用 safari 打开 index.html 时无显示

### ISSUE THREAD

**Issue by bindazhong** [ruanyf/react-demos#37]
mac os 下用 chrome 打开正常,用 safari 就没有显示.

**Comment by ruanyf** [comment]
which demo?

**Comment by ruanyf** [comment]
which demo?

**Comment by bindazhong** [comment]
solved .replace the browser.min.js  with <script src="http://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
