### ISSUE TITLE
git clone command is not correct

### ISSUE THREAD

**Issue by snowsky** [ruanyf/react-demos#4]
Should be as below:
git clone https://github.com/ruanyf/react-demos.git

**Comment by sarbbottam** [comment]
Not really, it depends on how you are cloning.

If you want to clone over ``HTTPS``, then url that you have specified, needs to be used.
However, if cloning over `SSH``, existing instruction is correct.

**Comment by snowsky** [comment]
@sarbbottam thx.

**Comment by parisqian-misa** [comment]
@ruanyf But why should we use `ssh` over `https`, I think https maybe more common and reliable to use. Plus, since most of windows do not pre-install ssh, the command will be very likely to fail on those machines
