### ISSUE TITLE
demo 11 里面的 this.isMounted 的作用是什么?

### ISSUE THREAD

**Issue by Nbsaw** [ruanyf/react-demos#43]
阮老师你好。我想请教下这一段里面的this.isMounted的作用。

https://github.com/ruanyf/react-demos/blob/15a5be3f3ef2e4de74531c8c97080ef977a91af7/demo11/index.html#L20-L30

看README的描述

> `did` methods which are called right after something happens.

`componentDidMount`这个钩子调用的时候` this.isMounted`应该总是为`true`吧。那么这个判断是不是多余的。

**Comment by ruanyf** [comment]
谢谢指出，这个判断确实是多余的。我把它删掉。

**Comment by vipcxj** [comment]
并不一定吧~ isMounted是在回调函数中，并且涉及网络请求，没人能保证它执行的时候仍旧是Mounted的

**Comment by Nbsaw** [comment]
@vipcxj `componentDidMount`是在`isMounted`状态为`true`的时候执行的回调函数,所以是可以保证的。我刚才仔细看了一下`README`的实例是正确的,有误的只是`demo11`文件夹里面的那个实例代码

**Comment by vipcxj** [comment]
@Nbsaw 没记错的话，应该是执行get网络请求后才调用的回调函数，如果网比较差，这就会有一个时间差了啊，如果期间被unmount了，也是可能的

**Comment by ruanyf** [comment]
理论上，获取到数据的时候，组件是可能被卸载的。但是，这个例子里，确实是多余的判断。

另外，`isMounted`这个 API 也已经被废掉了，所以还是去掉比较好。https://github.com/facebook/react/issues/5465

**Comment by vipcxj** [comment]
@ruanyf 我把整个issure都看了下，基本就是react的开发者嫌isMounted不够优雅，想废除它，但又没在react内部给一个完美的代替方案，所以另一个react的贡献者就不同意了。然后就是提出各种workaround，然而所有workaround都不是react自带的，全部仅仅是workaround～ 没看到这个issure的岂不是要被坑？

**Comment by ruanyf** [comment]
isMounted 确实被废掉了。https://github.com/facebook/react/blob/3c977dea6b96f6a9bb39f09886848da870748441/packages/react/src/ReactBaseClasses.js#L89
