### ISSUE TITLE
demo13  react 引入失败

### ISSUE THREAD

**Issue by nicefuting** [ruanyf/react-demos#45]
demo13中react和react-dom引入失败，fb链接已失效，将build中的react和react-dom放入src中，路径为‘./react.xxx.js’
，一直提示:    get http://localhost:3000/react-0.14.0.js net::ERR_ABORTED。不知道什么原因

**Comment by tonalll** [comment]
666

**Comment by ruanyf** [comment]
这个地址需要翻墙，我看看有没有国内的 CDN 地址。

**Comment by ruanyf** [comment]
你的本地文件要放在`demo13`目录下面。
