### ISSUE TITLE
为什么我运行demo13会有问题啊?

### ISSUE THREAD

**Issue by StephenWu5** [ruanyf/react-demos#46]
1.   问题:![image](https://user-images.githubusercontent.com/32475322/40337378-ebea8f10-5da1-11e8-8109-dd5ff3c922fc.png)

2.  问题:
![image](https://user-images.githubusercontent.com/32475322/40337398-0f31bb24-5da2-11e8-932b-d8d5336f2fe4.png)

软大神快来解答一下吧

**Comment by ruanyf** [comment]
1、warning 不用去管它，加个 key 属性就可以。
2、react 没有升级。
3、下次提问，请把我的名字写对。

**Comment by StephenWu5** [comment]
好的，谢谢了哈
