### ISSUE TITLE
React Demo's with Babel.js

### ISSUE THREAD

**Issue by SOSANA** [ruanyf/react-demos#5]
Hi,

Curious if you are accepting PR's for updated demo's using babel.js? or if you plan to update repo using babel.js

**Comment by ruanyf** [comment]
These demos are intended to keep simple. I don't think the transpiled source code by Babel would be helpful to reach this intention. In most cases, the un-babeled codes are better suitable for this repo.

**Comment by SOSANA** [comment]
As announced, starting with React v0.14 (next release), the JSXTransformer.js won't be part of the release. Also `react-tools` npm package is no more. 

I was more or less talking about updating the script src files, script tags
```
<script src="react/build/react.js"></script>
<script src="react/build/JSXTransformer.js"></script>
```
to this 
```
<script src="react/build/react.js"></script>
<script src="babel/browser.js"></script>
```

and

from this
```
type="text/jsx"
```

to this
```
type="text/babel"
```

**Comment by ruanyf** [comment]
@SOSANA，thanks for your reminder. I will update the demos when v0.14 is officially published.

**Comment by SOSANA** [comment]
Thanks broski, to javascript infinity and beyond!
