### ISSUE TITLE
$npm is not recognized as an internal or external command

### ISSUE THREAD

**Issue by enjoyjubilee** [ruanyf/react-demos#55]
After I git clone the ssh from github page and successfully installed the package, and I can open the file folder in Atom, I can not use the $npm install -g babel. I'm using windows 10 system.

The error message goes like this:
>User\Document\react-demos $npm install -g babel
'$npm' is not recognized as an internal or external command,
operable program or batch file.

New to JavaScript but rush to a final. Thanks in advance for your reply!

**Comment by ruanyf** [comment]
`$` is a command line prompt in a Unix-like system.

When using Windows, you should use the following command.

```
npm install -g babel
```
