### ISSUE TITLE
Dont need to use findDOMNode to refer a dom node

### ISSUE THREAD

**Issue by cwtuan** [ruanyf/react-demos#7]
In demo #7, 
You can just use 
```
this.refs.myTextInput
```

No need to use 
```
ReactDOM.findDOMNode(this.refs.myTextInput)
```

Please check: (https://facebook.github.io/react/docs/top-level-api.html#reactdom.finddomnode)

**Comment by ruanyf** [comment]
Thank you for your reminder. I have already corrected the demo.
