### ISSUE TITLE
React.Children.map 

### ISSUE THREAD

**Issue by cwtuan** [ruanyf/react-demos#8]
In Demo05, you mentioned,
```
Please be minded that only if the component has more than one child node,
you could take this.props.children as an array, 
otherwise this.props.children.map throws a TypeError.
```
It would be nice if you remind reader that there's a  function called React.Children.map which can deal with this problem well.

More info https://facebook.github.io/react/docs/top-level-api.html#react.children

**Comment by ruanyf** [comment]
Thanks for your reminder. I've already update the demo.
