### ISSUE TITLE
Please add functional component and demos of react hooks also

### ISSUE THREAD

**Issue by anasaijaz** [ruanyf/react-demos#80]

**Comment by forjuan** [comment]
你好！我已收到你的邮件。

**Comment by XurryAli** [comment]
您好，您的邮件已收到，这是自动回复邮件，看到邮件后，我会尽快给您回复，谢谢！

**Comment by Eastboat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ruanyf** [comment]
This repo is quite old to update. You should read the  official websute guide for new demos of functional React.

**Comment by jingxinxin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Eastboat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by forjuan** [comment]
你好！我已收到你的邮件。

**Comment by XurryAli** [comment]
您好，您的邮件已收到，这是自动回复邮件，看到邮件后，我会尽快给您回复，谢谢！

**Comment by PhoenixMenia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
