### ISSUE TITLE
Wrong class name?

### ISSUE THREAD

**Issue by ShimizuShiori** [ruanyf/react-demos#82]
I read your article.
It's very cool.

But maybe something is incorrect in the **Demo04: Define a component**

Maybe you want to give an example to show that the first lower case will generate an error.
But in your article, two examples are both start with the BIG H.

I feel that isn't your original proposal

**Comment by jingxinxin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by PhoenixMenia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by forjuan** [comment]
你好！我已收到你的邮件。

**Comment by ruanyf** [comment]
no, it is correct.
