### ISSUE TITLE
【React源码专题文章推荐】专注于React源码解析的文章

### ISSUE THREAD

**Issue by lizuncong** [ruanyf/react-demos#84]
寻找对react源码感兴趣的朋友。如果对 react 源码感兴趣的朋友，欢迎一起共建。如果有什么好的外文需要翻译，也可以加到 仓库read.me 中的TODO列表。或者觉得什么文章好，也欢迎提 PR 收录进来。希望能一起对文章质量把关，一起共建社区最好的 react 源码生态环境。

https://github.com/lizuncong/mini-react

**Comment by jingxinxin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by forjuan** [comment]
你好！我已收到你的邮件。

**Comment by PhoenixMenia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by XurryAli** [comment]
您好，您的邮件已收到，这是自动回复邮件，看到邮件后，我会尽快给您回复，谢谢！

**Comment by Eastboat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
