### ISSUE TITLE
为什么会有这么多星

### ISSUE THREAD

**Issue by pengjie-chen** [ruanyf/react-demos#86]
我感觉是比较基础的使用方法把，为啥有这么多star 不是很理解 小白一枚

**Comment by forjuan** [comment]
你好！我已收到你的邮件。

**Comment by PhoenixMenia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by XurryAli** [comment]
您好，您的邮件已收到，这是自动回复邮件，看到邮件后，我会尽快给您回复，谢谢！

**Comment by Eastboat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by FE-wuhao** [comment]
> 我感觉是比较基础的使用方法把，为啥有这么多star 不是很理解 小白一枚

比较系统吧，而且都附带了例子什么的 。虽然我也不记得当初是为什么star的了，但是肯定对初学的我有了很大的帮助☺

**Comment by pengjie-chen** [comment]
> 

soga
