### ISSUE TITLE
Important notes

### ISSUE THREAD

**Issue by dmowski** [ruanyf/react-demos#87]
ssss

**Comment by dmowski** [comment]
@xxxyyynnn @G-Milevski @xzlaptt @Madiy @kostyaostapuk @Bolshoff @goldenyak
@MishaMgla @deq406 @volodkovadim0 @Anton13602 @Anton-Shvetc


Hi folks

**Comment by jingxinxin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by forjuan** [comment]
你好！我已收到你的邮件。

**Comment by PhoenixMenia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by XurryAli** [comment]
您好，您的邮件已收到，这是自动回复邮件，看到邮件后，我会尽快给您回复，谢谢！

**Comment by Eastboat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
